### ISSUE TITLE
Create pptx

### ISSUE THREAD

**Issue by JonnyTech** [dam4rus/msoffice-pptx-rs#6]
Is this library suitable for programmatically creating `pptx` files? If so does an example exist? Looking to create a pptx file and insert several slides with images within them. Does `msoffice-pptx-rs` do that?

**Comment by dam4rus** [comment]
Not yet, but I plan to implement serialization support as well. This project is still WIP and kinda in a limbo right now. I realized that it's a pretty big subject for a single developer, especially as I work full time and work on other open source projects as well, so i'm kinda figuring out how to move forward.

**Comment by JonnyTech** [comment]
Cool, thanks for the feedback, looking forward to any updates as and when you get around to it.
